spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/studs'
    username: 1
    password: 2
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true